[[main]]
    name = "Overview"
    url = "/overview/"
    weight = 1
[[main]]
    name = "Apps"
    url = "/apps/"
    weight = 2
[[main]]
    name = "FAQ"
    url = "/faq/"
    weight = 3
[[main]]
    name = "Blog"
    url = "/blog/"
    weight = 4
[[main]]
    name = "About"
    url = "/about/"
    weight = 5